### ISSUE TITLE
-T warnings

### ISSUE THREAD

**Issue by pdxwolfy** [fsievers/linter-perl-check-syntax#1]
Hi,
I have a fair amount of code that runs with the -T option set by a "#!perl -T" shebang line. If you pass such a script through "perl -c" without also specifying the "-T" option, perl complains quite loudly. As a result, all of these script have one unfixed "issue" that reads:

[Perl][Error] "-T" is on the #! line, it must also be used on the command line

Do you think this package could handle that? I took a look at the code, and I _think_ it can be handled readily enough, but I've not yet done any Atom package development or Coffee programming, so I'm not too certain of myself. However, I'm willing to give it a shot myself if you don't want or don't have the time to do it.

Thanks for putting this package out there!

**Comment by fsievers** [comment]
I've added an option, to enable the '-T' command line options from settings. This way you can enable the tainted switch in case you need it. There should be no issue if you check your file with taint mode enabled, even if you don't need it.

**Comment by fsievers** [comment]
Closed with: https://github.com/fsievers/linter-perl-check-syntax/commit/af8af1bd8c8639aea5a99843ef7b5422f5eff31f

**Comment by pdxwolfy** [comment]
Thank you, Florian. Seems to work.
