### ISSUE TITLE
Unable to get it work

### ISSUE THREAD

**Issue by demanuel** [fsievers/linter-perl-check-syntax#4]
Hi!

I'm unable to get this working... Since i'm really new to Atom (i've been playing with it for less than 1 hour), i'm not sure if i'm doing something wrong...

I have this code:

```
use warnings;

sub test{
  my %hash=();

  %hash{123}=321;

  $var="asd;


}

```
And running perl -c on the command line returns:
```
[demanuel@localhost ~]$ perl -c test.pl 
Can't modify key/value hash slice in list assignment at test.pl line 6, near "321;"
test.pl had compilation errors.
[demanuel@localhost ~]$
```

But atom shows nothing :-(

![perl-linter](https://cloud.githubusercontent.com/assets/1687786/20652976/ddbd62d8-b504-11e6-8939-88717a693dfb.png)

How do i debug this? 

EDIT: I'm running atom 1.12.5

**Comment by fsievers** [comment]
There should be a bar at the bottom, that shows you the errors for a file and for the whole project. The linter shoud start, as soon as you save the file.
![linter-error-statusbar](https://cloud.githubusercontent.com/assets/2866107/20844477/430a5b0a-b8c0-11e6-986b-3fc9d312035c.png)

![linter-error-inline](https://cloud.githubusercontent.com/assets/2866107/20844483/4ac8897a-b8c0-11e6-83b8-3f7f00a34a04.png)

**Comment by demanuel** [comment]
This is still not working.
If it helps the message perl -c returns is

```
Can't modify key/value hash slice in list assignment at test.pl line 7, near "321;"
test.pl had compilation errors.
```

perl version: 5.24.0

**Comment by demanuel** [comment]
I don't know if this helps but i put an alert on the [line 15](https://github.com/fsievers/linter-perl-check-syntax/blob/master/lib/linter-perl-check-syntax.coffee#L15), and the popup never appears, so it seems that this isn't being "registered" or "called" (i haven't read the atom developers guide so i don't know what hooks they have..)... :-(

**Comment by fsievers** [comment]
Inserting an alert('test') in line 15 should open an alert box as soon as you open an perl file. 
![Alertmessage from line 15](https://cloud.githubusercontent.com/assets/2866107/20851189/2282e662-b8df-11e6-8790-a2d4f7030805.png)

I also installed Perl 5.24.0 via perlbrew and had no problems with the code.

Did you installed the linter package for Atom https://atom.io/packages/linter and enabled it?

**Comment by demanuel** [comment]
I installed it now and now it's working! :-D
Thank you!

Shouldn't be a warning that dependencies are missing? 
Thank you once more!

**Comment by fsievers** [comment]
I updated the README to show dependencies, that needs to be installed manualy.
