### ISSUE TITLE
Error running Perl Error: process execution timed out

### ISSUE THREAD

**Issue by DanFreed** [fsievers/linter-perl-check-syntax#5]
Please reference my original bug submitted to the linter bug list at: [https://github.com/steelbrain/linter/issues/1404]

I've started getting these errors on a somewhat regular basis (but not all of the time):

linter-registry.js [sm]:144 [Linter] Error running Perl Error: Process execution timed out
at /Users/dfreed/.atom/packages/linter-perl-check-syntax/node_modules/sb-exec/lib/index.js:92:18(anonymous function) @ linter-registry.js [sm]:144
6events.js:160 Uncaught Error: write EPIPE

The code being listed is on an SMB share, so I'm guessing it has something to do with how fast/slow that network connection is.

Is there a way to increase the timeout?

The linter author said to relay the following:

Please contact the author of linter-perl-check-syntax asking for a timeout increase, tell the author that they can do so by supplying timeout: 60000 in atom-linter's exec/execNode method

**Comment by fsievers** [comment]
I added an option to set the timeout via configuration dialog of linter-perl-check-syntax.
